# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calender_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('check_1', models.CharField(default='0', max_length=15)),
                ('check_2', models.CharField(default='0', max_length=15)),
                ('check_3', models.CharField(default='0', max_length=15)),
                ('check_4', models.CharField(default='0', max_length=15)),
                ('check_5', models.CharField(default='0', max_length=15)),
                ('check_6', models.CharField(default='0', max_length=15)),
                ('check_7', models.CharField(default='0', max_length=15)),
                ('check_8', models.CharField(default='0', max_length=15)),
                ('check_9', models.CharField(default='0', max_length=15)),
                ('check_10', models.CharField(default='0', max_length=15)),
                ('check_11', models.CharField(default='0', max_length=15)),
                ('check_12', models.CharField(default='0', max_length=15)),
                ('check_13', models.CharField(default='0', max_length=15)),
                ('check_14', models.CharField(default='0', max_length=15)),
                ('check_15', models.CharField(default='0', max_length=15)),
                ('check_16', models.CharField(default='0', max_length=15)),
            ],
        ),
    ]
