# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlist',
            name='calender_id',
        ),
        migrations.AddField(
            model_name='requestlist',
            name='date1',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='month1',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='sport1',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
