# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administer', '0002_auto_20180412_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlist',
            name='purpose',
            field=models.CharField(default='Not Provided', max_length=10000),
        ),
    ]
