# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-13 06:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administer', '0003_requestlist_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlist',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 13, 12, 19, 24, 105968)),
        ),
    ]
