# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-13 06:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administer', '0004_requestlist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlist',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 13, 12, 20, 5, 87413)),
        ),
    ]
