# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-13 06:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administer', '0005_auto_20180413_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlist',
            name='date',
        ),
        migrations.AddField(
            model_name='requestlist',
            name='date2',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 13, 12, 21, 20, 772692)),
        ),
    ]
