# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-13 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administer', '0008_auto_20180413_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlist',
            name='date2',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 13, 18, 23, 15, 404752)),
        ),
    ]
