# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-11 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180411_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='check_1',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='calender',
            name='check_10',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='calender',
            name='check_11',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='calender',
            name='check_12',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='calender',
            name='check_13',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='calender',
            name='check_14',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='calender',
            name='check_15',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='calender',
            name='check_16',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='calender',
            name='check_2',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='calender',
            name='check_3',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='calender',
            name='check_4',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='calender',
            name='check_5',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='calender',
            name='check_6',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='calender',
            name='check_7',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='calender',
            name='check_8',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='calender',
            name='check_9',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
