# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-11 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180411_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='req_user_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='calender',
            name='req_user_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='calender',
            name='req_user_3',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
