# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180412_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='purpose',
            field=models.CharField(default='Not Provided', max_length=10000),
        ),
    ]
