# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-13 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180413_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='total_bookings',
            field=models.IntegerField(default=0),
        ),
    ]
